"""Add prepaid billing

Revision ID: 37bd79603119
Revises: 4580753c07e3
Create Date: 2026-03-15 13:30:04.782118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bd79603119'
down_revision = '4580753c07e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create Enums explicitly for Postgres
    billing_mode = sa.Enum('Postpaid', 'Prepaid', name='billingmode')
    billing_mode.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prepaid_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('amount_kwh', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('TopUp', 'Deduction', name='prepaidtransactiontype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['renter_id'], ['renters.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['charging_sessions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepaid_transactions_id'), 'prepaid_transactions', ['id'], unique=False)
    op.add_column('billing_settings', sa.Column('billing_mode', sa.Enum('Postpaid', 'Prepaid', name='billingmode'), server_default='Postpaid', nullable=False))
    op.add_column('renters', sa.Column('prepaid_balance_kwh', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('renters', 'prepaid_balance_kwh')
    op.drop_column('billing_settings', 'billing_mode')
    op.drop_index(op.f('ix_prepaid_transactions_id'), table_name='prepaid_transactions')
    op.drop_table('prepaid_transactions')
    # ### end Alembic commands ###

    # Drop Enums
    billing_mode = sa.Enum('Postpaid', 'Prepaid', name='billingmode')
    billing_mode.drop(op.get_bind(), checkfirst=True)

    transaction_type = sa.Enum('TopUp', 'Deduction', name='prepaidtransactiontype')
    transaction_type.drop(op.get_bind(), checkfirst=True)
