"""Add last_seen to charging_stations

Revision ID: 3ac7884d5522
Revises: 37bd79603119
Create Date: 2026-03-15 20:40:06.166338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac7884d5522'
down_revision = '37bd79603119'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_stations', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_stations', 'last_seen')
    # ### end Alembic commands ###
