"""Add billing_settings table

Revision ID: 4580753c07e3
Revises: c9c868a275a4
Create Date: 2026-03-15 11:52:03.100950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4580753c07e3'
down_revision = 'c9c868a275a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('iban', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('periodicity', sa.Enum('Monthly', 'Quarterly', 'HalfYearly', 'Yearly', name='billingperiodicity'), nullable=True),
    sa.Column('price_per_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_settings_id'), 'billing_settings', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['renter_id'], ['renters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.add_column('charging_sessions', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'charging_sessions', 'invoices', ['invoice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charging_sessions', type_='foreignkey')
    op.drop_column('charging_sessions', 'invoice_id')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_billing_settings_id'), table_name='billing_settings')
    op.drop_table('billing_settings')
    # ### end Alembic commands ###
