"""add_connector_id_to_session

Revision ID: 657dcf3212d2
Revises: c3c82031330d
Create Date: 2025-12-31 17:53:26.983560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657dcf3212d2'
down_revision = 'c3c82031330d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_sessions', sa.Column('connector_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_sessions', 'connector_id')
    # ### end Alembic commands ###
