"""Add kiosk_mode to ChargingStation

Revision ID: 885360aff9bb
Revises: 974e962c504a
Create Date: 2026-03-01 20:44:26.294014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885360aff9bb'
down_revision = '974e962c504a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relay_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('encrypted_token', sa.String(), nullable=True),
    sa.Column('relay_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relay_settings_id'), 'relay_settings', ['id'], unique=False)
    op.add_column('charging_stations', sa.Column('kiosk_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_stations', 'kiosk_mode')
    op.drop_index(op.f('ix_relay_settings_id'), table_name='relay_settings')
    op.drop_table('relay_settings')
    # ### end Alembic commands ###
