"""Initial Schema

Revision ID: 8d59fec0132a
Revises: 
Create Date: 2025-12-28 15:36:46.622470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d59fec0132a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_stations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charging_stations_id'), 'charging_stations', ['id'], unique=False)
    op.create_table('renters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renters_id'), 'renters', ['id'], unique=False)
    op.create_table('authorization_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('renter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Accepted', 'Blocked', 'Expired', 'Invalid', 'ConcurrentTx', name='authorizationstatus'), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['renter_id'], ['renters.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_authorization_tokens_token'), 'authorization_tokens', ['token'], unique=False)
    op.create_table('boot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('boot_time', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boot_logs_id'), 'boot_logs', ['id'], unique=False)
    op.create_table('parking_spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('floor_level', sa.String(), nullable=True),
    sa.Column('renter_id', sa.Integer(), nullable=True),
    sa.Column('charging_station_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['charging_station_id'], ['charging_stations.id'], ),
    sa.ForeignKeyConstraint(['renter_id'], ['renters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charging_station_id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_parking_spots_id'), 'parking_spots', ['id'], unique=False)
    op.create_table('station_configurations',
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('readonly', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'key')
    )
    op.create_table('station_connectors',
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Available', 'Preparing', 'Charging', 'SuspendedEVSE', 'SuspendedEV', 'Finishing', 'Reserved', 'Unavailable', 'Faulted', name='chargingstationstatus'), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'connector_id')
    )
    op.create_table('charging_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('meter_start', sa.Integer(), nullable=False),
    sa.Column('meter_stop', sa.Integer(), nullable=True),
    sa.Column('total_energy_kwh', sa.Float(), nullable=True),
    sa.Column('stop_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['authorization_tokens.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charging_sessions_id'), 'charging_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_charging_sessions_transaction_id'), 'charging_sessions', ['transaction_id'], unique=True)
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('measurand', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['charging_sessions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_id'), 'meter_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meter_readings_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    op.drop_index(op.f('ix_charging_sessions_transaction_id'), table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_id'), table_name='charging_sessions')
    op.drop_table('charging_sessions')
    op.drop_table('station_connectors')
    op.drop_table('station_configurations')
    op.drop_index(op.f('ix_parking_spots_id'), table_name='parking_spots')
    op.drop_table('parking_spots')
    op.drop_index(op.f('ix_boot_logs_id'), table_name='boot_logs')
    op.drop_table('boot_logs')
    op.drop_index(op.f('ix_authorization_tokens_token'), table_name='authorization_tokens')
    op.drop_table('authorization_tokens')
    op.drop_index(op.f('ix_renters_id'), table_name='renters')
    op.drop_table('renters')
    op.drop_index(op.f('ix_charging_stations_id'), table_name='charging_stations')
    op.drop_table('charging_stations')
    # ### end Alembic commands ###
