"""make token_id nullable in charging_sessions

Revision ID: a9af84f42f2d
Revises: 885360aff9bb
Create Date: 2026-03-01 21:23:26.591806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9af84f42f2d'
down_revision = '885360aff9bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('charging_sessions', 'token_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('charging_sessions_token_id_fkey'), 'charging_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'charging_sessions', 'authorization_tokens', ['token_id'], ['token'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charging_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('charging_sessions_token_id_fkey'), 'charging_sessions', 'authorization_tokens', ['token_id'], ['token'])
    op.alter_column('charging_sessions', 'token_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
