"""add snapshot columns to charging_session

Revision ID: c9c868a275a4
Revises: a9af84f42f2d
Create Date: 2026-03-01 21:33:02.941227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c868a275a4'
down_revision = 'a9af84f42f2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_sessions', sa.Column('token_snapshot', sa.String(), nullable=True))
    op.add_column('charging_sessions', sa.Column('renter_name_snapshot', sa.String(), nullable=True))
    op.add_column('charging_sessions', sa.Column('renter_email_snapshot', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charging_sessions', 'renter_email_snapshot')
    op.drop_column('charging_sessions', 'renter_name_snapshot')
    op.drop_column('charging_sessions', 'token_snapshot')
    # ### end Alembic commands ###
