"""Add Unknown status and make renter_id nullable

Revision ID: da572f8424b5
Revises: 657dcf3212d2
Create Date: 2026-01-18 13:48:12.069305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da572f8424b5'
down_revision = '657dcf3212d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorization_tokens', 'renter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorization_tokens', 'renter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
