"""Initial Schema

Revision ID: f4c2d9ce06b9
Revises: 6a21efa70fe0
Create Date: 2025-12-29 10:08:35.979552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c2d9ce06b9'
down_revision = '6a21efa70fe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE chargingstationstatus ADD VALUE 'Unknown'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
